apiVersion: v1
kind: Service
metadata:
  name: {{ include "jukebox-data-manager-grpc.fullname" . }}
  labels:
    {{- include "jukebox-data-manager-grpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "jukebox-data-manager-grpc.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc-http2
      port: {{ .Values.service.http2Port }}
      targetPort: grpc-http2
      nodePort: {{ .Values.service.nodePort.http2 }}
    - name: grpc-h1h2
      port: {{ .Values.service.http1AndHttp2Port }}
      targetPort: grpc-h1h2
      nodePort: {{ .Values.service.nodePort.http1AndHttp2 }}
