apiVersion: v1
kind: Service
metadata:
  name: {{ include "jukebox-data-manager-rest.fullname" . }}
  labels:
    {{- include "jukebox-data-manager-rest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "jukebox-data-manager-rest.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
